export const apiPath = {
  GET_USER_LIST: "/api/QuanLyNguoiDung/LayDanhSachNguoiDung_PhanTrang",
  ADD_USER: "/api/QuanLyNguoiDung/ThemNguoiDung",
  GET_LIST_TYPE_USER: "/api/QuanLyNguoiDung/LayDanhSachLoaiNguoiDung",
  SIGN_IN: "/api/QuanLyNguoiDung/DangNhap",
  SIGN_UP: "/api/QuanLyNguoiDung/DangKy",
  DELETE_USER: "/api/QuanLyNguoiDung/XoaNguoiDung",
  UPDATE_USER: "/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung",
  SEARCH_USER: "/api/QuanLyNguoiDung/TimKiemNguoiDung",
  GET_ALL_USER_LIST: "/api/QuanLyNguoiDung/LayDanhSachNguoiDung",
  GET_COURSE_LIST: "/api/QuanLyKhoaHoc/LayDanhSachKhoaHoc_PhanTrang",
  ADD_COURSE: "/api/QuanLyKhoaHoc/ThemKhoaHoc",
  ACCOUNT_INFO: "/api/QuanLyNguoiDung/ThongTinNguoiDung",
  CATEGORY_COURSE: "/api/QuanLyKhoaHoc/LayDanhMucKhoaHoc",
  UPLOAD_IMAGE_COURSE: "/api/QuanLyKhoaHoc/UploadHinhAnhKhoaHoc",
  DELETE_COURSE: "/api/QuanLyKhoaHoc/XoaKhoaHoc",
  DETAIL_COURSE: "/api/QuanLyKhoaHoc/LayThongTinKhoaHoc",
  UPDATE_COURSE: "/api/QuanLyKhoaHoc/CapNhatKhoaHoc",
  UPDATE_COURSE_UPLOAD_IMAGE: "/api/QuanLyKhoaHoc/CapNhatKhoaHocUpload",
  GET_COURSE_CATEGORY: "/api/QuanLyKhoaHoc/LayKhoaHocTheoDanhMuc",
  GET_COURSE_LIST_PAGE: "/api/QuanLyKhoaHoc/LayDanhSachKhoaHoc_PhanTrang",
  REGISTER_COURSE: "/api/QuanLyKhoaHoc/DangKyKhoaHoc",
  CANCEL_REGISTER: "/api/QuanLyKhoaHoc/HuyGhiDanh",
  GET_USER_LIST_NOT_REGISTER:
    "/api/QuanLyNguoiDung/LayDanhSachNguoiDungChuaGhiDanh",
  GET_USER_LIST_REGISTER: "/api/QuanLyNguoiDung/LayDanhSachHocVienKhoaHoc",
  GET_USER_LIST_APPROVE: "/api/QuanLyNguoiDung/LayDanhSachHocVienChoXetDuyet",
  CONFIRM_REGISTER_COURSE: "/api/QuanLyKhoaHoc/GhiDanhKhoaHoc",
  GET_COURSE_NOT_REGISTER: "/api/QuanLyNguoiDung/LayDanhSachKhoaHocChuaGhiDanh",
  GET_COURSE_LIST_APPROVED: "/api/QuanLyNguoiDung/LayDanhSachKhoaHocDaXetDuyet",
  GET_COURSE_LIST_WAIT_APPROVE:
    "/api/QuanLyNguoiDung/LayDanhSachKhoaHocChoXetDuyet",
};
